"""
ExportEngine — generates real-world deployable artifacts from a completed simulation.

Outputs:
  1. CLI Script (SW1 + SW2) — paste directly into VOSS terminal or upload as .xsf
  2. XIQ Policy JSON — importable into XIQ Network Policy > Fabric Connect
  3. Deployment Checklist — step-by-step verification commands

This is the "flight simulator to real aircraft" bridge.
A simulation session that ends with green exports means the student
is ready to execute on physical hardware with zero guesswork.
"""

from __future__ import annotations
import json
from datetime import datetime
from simulator.models.lab_state import LabState
from simulator.config import SERVICES, SWITCHES, SPBM, PORTS, MODEM_IP, INTERNET_EXIT_VLAN


class ExportEngine:

    def __init__(self, lab: LabState, student_name: str = ""):
        self.lab = lab
        self.student_name = student_name
        self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    # ── CLI Scripts ───────────────────────────────────────────────────────────

    def cli_script(self, switch_id: str) -> str:
        sw_cfg = SWITCHES[switch_id]
        is_sw1 = switch_id == "SW1"
        lines = [
            "!" * 70,
            f"! VOSS/FabricEngine Configuration Script — {switch_id}",
            f"! Generated by FabricEngine Flight Simulator",
            f"! Student: {self.student_name or 'Lab Engineer'}",
            f"! Date:    {self.generated_at}",
            "!",
            "! PREREQUISITES BEFORE PASTING:",
            "!   1. OS changed to VOSS via XIQ (Actions > Change OS) or boot menu",
            "!   2. Switch registered and connected in XIQ",
            "!   3. Serial console connected at 115200 baud",
            "!   4. Login: rwa / rwa (FabricEngine default)",
            "!",
            "! REFERENCE:",
            f"!   EXOS baseline: https://khursheedkhanaiforgood-ai.github.io/5320-onboarding/",
            f"!   Apr 8 E2E:     https://khursheedkhanaiforgood-ai.github.io/5320-onboarding/session_log_20260408.html",
            "!" * 70,
            "",
            "enable",
            "configure terminal",
            "",
            "! ─── PHASE 2: SPB CONTROL PLANE (IEEE 802.1aq + RFC 6329) ────────────",
            "router isis",
            f" system-id {sw_cfg['system_id']}",
            f" manual-area {SPBM['manual_area']}",
            " exit",
            "",
            f"spbm {SPBM['instance']}",
            f" nick-name {sw_cfg['nick_name']}",
            f" ethertype {SPBM['ethertype']}",
            " exit",
            "",
            "router isis enable",
            "",
            f"! ─── NNI PORT (Port {PORTS['nni']}) — Fabric backbone ────────────────",
            f"interface gigabitEthernet 1/{PORTS['nni']}",
            " isis enable",
            " isis network point-to-point",
            " no shutdown",
            "exit",
            "",
            "! ─── SERVICE VLANS + I-SID BINDINGS (IEEE 802.1aq §12) ─────────────",
        ]

        # VLANs
        vlan_ids = " ".join(str(v) for v in sorted(SERVICES.keys()))
        lines.append(f"vlan create {vlan_ids.replace(' ', ',')} type port-mstprstp 0")
        for vlan_id, svc in sorted(SERVICES.items()):
            lines.append(f"vlan name {vlan_id} \"{svc['name']}\"")
        lines.append("")
        for vlan_id, svc in sorted(SERVICES.items()):
            lines.append(f"vlan i-sid {vlan_id} {svc['isid']}")

        lines += [
            "",
            "! ─── ANYCAST GATEWAYS (same IP on both switches) ────────────────────",
        ]
        for vlan_id, svc in sorted(SERVICES.items()):
            gw = svc["gateway"]
            lines.append(f"interface vlan {vlan_id}")
            lines.append(f" ip address {gw}/24")
            if is_sw1 and vlan_id != 10:
                lines.append(" ip dhcp-server enable")
            lines.append("exit")

        if is_sw1:
            lines += [
                "",
                "! ─── DHCP SERVER (SW1 authoritative — SW2 clients use fabric relay) ──",
                "ip dhcp-server enable",
            ]
            for vlan_id, svc in sorted(SERVICES.items()):
                if vlan_id == 10:
                    continue
                pool_name = svc["name"]
                subnet = svc["subnet"].split("/")[0]
                gw = svc["gateway"]
                range_start = gw.rsplit(".", 1)[0] + ".100"
                range_end   = gw.rsplit(".", 1)[0] + ".200"
                lines += [
                    f"ip dhcp-server pool {pool_name}",
                    f" network-address {subnet} 255.255.255.0",
                    f" range {range_start} {range_end}",
                    f" default-router {gw}",
                    " dns-server 8.8.8.8 8.8.4.4",
                    " exit",
                ]

        lines += [
            "",
            "! ─── FABRIC ATTACH — AP3000 Port (IEEE 802.1Qcj) ──────────────────",
            "fa enable",
            f"interface gigabitEthernet 1/{PORTS['ap3000']}",
            " auto-sense enable",
            " fa enable",
            " no shutdown",
            "exit",
            "",
            "! ─── INTERNET EXIT (Port 1 → Quantum Fiber modem) ──────────────────",
            f"vlan create {INTERNET_EXIT_VLAN} name Internet_Exit type port-mstprstp 0",
            f"vlan members add {INTERNET_EXIT_VLAN} 1/{PORTS['modem']}",
            f"interface vlan {INTERNET_EXIT_VLAN}",
            f" ip address {sw_cfg['internet_vlan_ip']}/24",
            "exit",
            f"ip route 0.0.0.0 0.0.0.0 {MODEM_IP} weight 1 enable",
            "",
            "! ─── IP SHORTCUTS (SW2 learns SW1 default route via fabric) ─────────",
            "router isis",
            " ip-shortcut",
            "exit",
            "",
            "! ─── SAVE ───────────────────────────────────────────────────────────",
            "save config",
            "",
            "! ─── VERIFICATION COMMANDS ──────────────────────────────────────────",
            "! show isis adjacency          ! State must be UP (L1L2)",
            "! show fa assignment           ! State: ACTIVE, Type: DYNAMIC",
            "! show spbm                    ! ethertype must be 0x8100",
            "! show ip route                ! 0.0.0.0/0 via 192.168.1.1",
            "! show application iqagent status  ! Connection: Connected",
            "! show i-sid                   ! 5 VLANs, Type=ELAN",
            "!" * 70,
        ]

        return "\n".join(lines)

    # ── XIQ Policy JSON ───────────────────────────────────────────────────────

    def xiq_policy_json(self) -> str:
        """
        XIQ Network Policy JSON — import via Configure > Network Policies.
        Maps to Fabric Connect settings in XIQ's Switching > Device Template.
        """
        policy = {
            "_comment": "FabricEngine Flight Simulator — XIQ Network Policy Export",
            "_generated": self.generated_at,
            "_student": self.student_name,
            "_reference": "https://khursheedkhanaiforgood-ai.github.io/5320-onboarding/",
            "policy_name": "FabricEngine_Migration_Lab",
            "fabric_connect": {
                "enabled": True,
                "spbm_instance": SPBM["instance"],
                "ethertype": SPBM["ethertype"],
                "manual_area": SPBM["manual_area"],
                "switches": [
                    {
                        "switch_id": "SW1",
                        "system_id": SWITCHES["SW1"]["system_id"],
                        "nick_name": SWITCHES["SW1"]["nick_name"],
                        "role": "BEB + DHCP server + internet exit",
                    },
                    {
                        "switch_id": "SW2",
                        "system_id": SWITCHES["SW2"]["system_id"],
                        "nick_name": SWITCHES["SW2"]["nick_name"],
                        "role": "BEB + internet exit (redundant)",
                    },
                ],
            },
            "vlans": [
                {
                    "vlan_id": vid,
                    "name": svc["name"],
                    "isid": svc["isid"],
                    "gateway": svc["gateway"],
                    "subnet": svc["subnet"],
                    "standard": "IEEE 802.1aq §12 — I-SID E-LAN service binding",
                }
                for vid, svc in sorted(SERVICES.items())
            ],
            "port_templates": {
                "nni": {
                    "port": PORTS["nni"],
                    "type": "NNI",
                    "isis_enabled": True,
                    "isis_network": "point-to-point",
                    "standard": "RFC 6329 — IS-IS Extensions for SPB",
                },
                "ap_port": {
                    "port": PORTS["ap3000"],
                    "type": "Auto-Sense + Fabric Attach",
                    "auto_sense": True,
                    "fa_enabled": True,
                    "standard": "IEEE 802.1Qcj — Fabric Attach",
                },
                "internet_exit": {
                    "port": PORTS["modem"],
                    "type": "Access",
                    "vlan": INTERNET_EXIT_VLAN,
                    "note": "Quantum Fiber modem — 192.168.1.1",
                },
            },
            "xiq_steps": [
                "1. Configure > Network Policies > New Policy",
                "2. Switching > Common Settings > Enable Fabric Connect (SPBM)",
                "3. Set Manual Area: 00.0001",
                "4. Device Template: Port 17=NNI, Port 3=Auto-Sense+FA, Port 1=Access",
                "5. Fabric Attach section: map VLAN ID → I-SID for each SSID",
                "6. Manage > Devices > SW1 + SW2 > Actions > Change OS → VOSS",
                "7. After reboot: Perform Complete Configuration Update",
                "8. Manage > Devices > AP3000 > Update Config",
            ],
        }
        return json.dumps(policy, indent=2)

    # ── Deployment Checklist ──────────────────────────────────────────────────

    def deployment_checklist(self) -> str:
        lines = [
            "=" * 70,
            "FABRICENGINE MIGRATION — DEPLOYMENT CHECKLIST",
            f"Generated: {self.generated_at}  |  Student: {self.student_name}",
            "=" * 70,
            "",
            "PHASE 1 — OS CONVERSION",
            "─" * 40,
            "[ ] Backup SW1 EXOS config: save configuration as-script sw1_backup.xsf",
            "[ ] Copy to USB: cp /usr/local/cfg/sw1_backup.xsf /usr/local/ext/",
            "[ ] Backup SW2 EXOS config: save configuration as-script sw2_backup.xsf",
            "[ ] Create XIQ backup: Manage > Devices > Backups > Create Backup",
            "[ ] Clone Network Policy: EXOS_Pre_Migration_Backup",
            "[ ] XIQ: Actions > Change OS > VOSS on SW1 — DESTRUCTIVE",
            "[ ] XIQ: Actions > Change OS > VOSS on SW2 — DESTRUCTIVE",
            "[ ] Verify VOSS boot: show version (FabricEngine 8.x)",
            "[ ] Verify XIQ re-adoption: show application iqagent status (Connected)",
            "",
            "PHASE 2 — FABRIC CONFIGURATION (paste CLI scripts)",
            "─" * 40,
            "[ ] SW1: Paste sw1_config.voss → verify no errors",
            "[ ] SW2: Paste sw2_config.voss → verify no errors",
            "",
            "PHASE 2 VERIFICATION",
            "─" * 40,
            "[ ] SW1+SW2: show isis adjacency  → State: UP (L1L2)",
            "[ ] SW1+SW2: show spbm            → ethertype: 0x8100",
            "[ ] SW1+SW2: show i-sid           → 5 services, Type: ELAN",
            "[ ] SW1+SW2: show fa neighbor     → AP3000 visible on Port 1/3",
            "[ ] SW1+SW2: show fa assignment   → State: ACTIVE, Type: DYNAMIC",
            "[ ] SW1:     show ip route        → 0.0.0.0/0 via 192.168.1.1",
            "[ ] SW2:     show ip route        → 0.0.0.0/0 via IS-IS (ip-shortcut)",
            "[ ] SW1:     show ip dhcp-server summary → 4 pools active",
            "",
            "PHASE 3 — E2E VERIFICATION",
            "─" * 40,
            "[ ] Connect iPhone to Alpha SSID (VLAN 20) → DHCP 10.0.20.x → internet",
            "[ ] Connect iPhone to Bravo SSID (VLAN 30) → DHCP 10.0.30.x → internet",
            "[ ] Connect iPhone to Delta SSID (VLAN 50) → DHCP 10.0.50.x → internet",
            "[ ] Connect iPhone to Gamma SSID (VLAN 60) → DHCP 10.0.60.x → internet",
            "[ ] SW1+SW2: show application iqagent status → Connection: Connected",
            "",
            "CONVERGENCE TEST (Optional)",
            "─" * 40,
            "[ ] Start continuous ping from iPhone",
            "[ ] Unplug NNI cable (Port 17)",
            "[ ] Verify < 1s drop (traffic reroutes via local modem)",
            "[ ] Reconnect NNI → verify auto-recovery",
            "",
            "STANDARDS VERIFIED IN THIS DEPLOYMENT",
            "─" * 40,
            "[ ] IEEE 802.1aq  — Shortest Path Bridging (SPB control plane)",
            "[ ] RFC 6329      — IS-IS Extensions for SPB",
            "[ ] IEEE 802.1ah  — MAC-in-MAC data plane encapsulation",
            "[ ] IEEE 802.1Qcj — Fabric Attach (AP3000 auto-provisioning)",
            "[ ] IEEE 802.1ag  — OAM (connectivity fault management)",
            "=" * 70,
            "REFERENCE: https://khursheedkhanaiforgood-ai.github.io/5320-onboarding/",
            "=" * 70,
        ]
        return "\n".join(lines)
